# Generated by Django 2.2 on 2020-06-11 15:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vacancy',
            managers=[
                ('r', django.db.models.manager.Manager()),
            ],
        ),
    ]
